### ISSUE TITLE
Question about function chaining part

### ISSUE THREAD

**Issue by HelloWorldGitHubUser** [rcslab/orcbench#1]
hi,I'm wondering if this code includes the part about 'function chaining' (or building the function call graph), which is introduced in your paper? Maybe I've missed out sth but it seems that I couldn't find this part in your code😭😭

**Comment by krhancoc** [comment]
Hey!

We are currently working on weaving this into the new orcbench. The first iteration of orcbench was definitely a research project and not easily usable by anyone but us. I had re-factored orcbench to be much more usable but pulled out chaining till it was also refactored. This should re-introduced soon and waiting on a push request for it here.

I do not have an exact date on this, but I hope it will be in the next couple of weeks.

**Comment by HelloWorldGitHubUser** [comment]
Ohhh I see,thx a lot!!
